language: java

cache:
  directories:
    - $HOME/.m2

deploy:

- provider: codedeploy
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  revision_type: github
  application: TINATODO
  deployment_group: DT
  region: eu-west-1
  on:
    branch: backend-endpoints

script:
- ./mvnw clean install -B
